version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_URL=jdbc:mysql://db:3306/UMSD
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_DATABASE=UMSD
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
